apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lightllm-chart.fullname" . }}
  labels:
    {{- include "lightllm-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lightllm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lightllm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lightllm-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            ["python", "-m", "lightllm.server.api_server"]
          args:
            {{- if .Values.lightllm.startupArgs.model_dir }}
            - "--model_dir"
            - "{{ .Values.lightllm.startupArgs.model_dir }}"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.host }}
            - "--host"
            - "{{ .Values.lightllm.startupArgs.host }}"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.port }}
            - "--port"
            - "{{ .Values.lightllm.startupArgs.port | toString }}"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.nccl_port }}
            - "--nccl_port"
            - "{{ .Values.lightllm.startupArgs.nccl_port | toString }}"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.tp }}
            - "--tp"
            - "{{ .Values.lightllm.startupArgs.tp | toString }}"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.max_req_input_len }}
            - "--max_req_input_len"
            - "{{ .Values.lightllm.startupArgs.max_req_input_len | toString }}"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.max_req_total_len }}
            - "--max_req_total_len"
            - "{{ .Values.lightllm.startupArgs.max_req_total_len | toString }}"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.max_total_token_num }}
            - "--max_total_token_num"
            - "{{ .Values.lightllm.startupArgs.max_total_token_num | toString }}"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.tokenizer_mode }}
            - "--tokenizer_mode"
            - "{{ .Values.lightllm.startupArgs.tokenizer_mode }}"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.use_dynamic_prompt_cache }}
            - "--use_dynamic_prompt_cache"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.trust_remote_code }}
            - "--trust_remote_code"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.mode }}
            - "--mode"
            - "{{ .Values.lightllm.startupArgs.mode }}"
            {{- end }}
            {{- if .Values.lightllm.startupArgs.data_type }}
            - "--data_type"
            - "{{ .Values.lightllm.startupArgs.data_type }}"
            {{- end }}
            {{- if .Values.lightllm.additionalArgs }}
            {{- range $arg := splitList " " .Values.lightllm.additionalArgs }}
            - "{{ $arg }}"
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: model-data
              mountPath: {{ .Values.modelData.mountPath }}
      volumes:
        - name: model-data
          persistentVolumeClaim:
            claimName: {{ include "lightllm-chart.fullname" . }}-model-data
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
