apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lightllm-chart.fullname" . }}-model-data
  labels:
    {{- include "lightllm-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.modelData.accessModes | nindent 4 }}
  storageClassName: {{ .Values.modelData.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.modelData.size }}

